# Generated by Django 4.2.5 on 2023-10-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuproducts',
            old_name='Category',
            new_name='category',
        ),
    ]
