# Generated by Django 4.2.5 on 2023-10-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_amenity_hotel_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='table_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
